#!/usr/bin/env python3
import os

h = set()

s = ""

def display(page_num):
    first = f"- {'~~' if page_num else ''}"
    second = f"[{title_string.split('.')[0].title()}]"
    third = f"({file_name}){'~~' if page_num else ''} {f'Finished: {page_num}' if page_num else ''}"
    return first + second + third + "\n\n"


for root, dirs, files in os.walk("src"):
    dirs.sort()
    files.sort()
    for name in files:
        rel_dir = os.path.relpath(root, ".")
        file_name = os.path.join(rel_dir, name)
        if file_name.lower().endswith(
            ("index.html", "completed.html", "template.html")
        ):
            continue
        elif file_name.lower().endswith((".md", ".epub", ".url")):
            split_file_name = file_name.split(".")
            if root[2:] not in h:
                h.add(root[2:])
                s += f"## {root[2:].title().replace('-', ' ').replace('/', ' > ')}\n\n"
            title_string = name.replace("-", " ").replace("_", " ")

with open("src/index.md", "w+") as f:
    f.write(s)

os.system("pandoc src/index.md --metadata title='RFCs' --template=templates/index.html -o site/index.html >/dev/null 2>&1")
